apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  creationTimestamp: null
  name: cicd-event-listener
  namespace: gitops166-cicd
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - name: github-push-binding
    interceptors:
    - github:
        secretRef:
          namespace: gitops166-cicd
          secretKey: webhook-secret-key
          secretName: gitops-webhook-secret
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'ishitasequeira/gitops166')
        overlays:
        - expression: split(body.ref,'/')[2]
          key: ref
    name: ci-dryrun-from-push
    template:
      name: ci-dryrun-from-push-template
  - bindings:
    - name: gitops166-dev-taxi-binding
    - name: github-push-binding
    interceptors:
    - github:
        secretRef:
          namespace: gitops166-cicd
          secretKey: webhook-secret-key
          secretName: webhook-secret-gitops166-dev-taxi
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'ishitasequeira/taxi')
        overlays:
        - expression: split(body.ref,'/')[2]
          key: ref
    name: app-ci-build-from-push-taxi
    template:
      name: app-ci-template
status:
  configuration:
    generatedName: ""
