apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: aug-cicd
spec:
  encryptedData:
    webhook-secret-key: AgBLbTyYcG0hwhiJnm/dqDc9/Z0tm7m2KeykHWnDUcP/F3nhbECMkQrvTtqaxcqWamI4QuU1kXM1Ue3a0TuxSJ4D6d03jFL3byTlxP5WI6WpB2gVNnwe5ArqTumR/FcR/T6erp+rjXlzJdVzzZpfdLBRv5ugQXZYM+NpfCmDsTbz+Fpz1eIy2Mk/umG0BTrGI7Zb8cOXxKdrr39TbduIwTJWUvePFp2bf3Yreu5xmnVnW/MuEg6VWelQ3/crLqE8akLpjBc69bjVWplaQygFtMXOEfNyQT6k9V8Y8sOECPiH7mtlnpcjGNHc96j0LY7alr9GdPB0vs311POjVFUd03628om/2UfntZf0+dr8ckTNK2iMBMTXeuWWynsoLcqoeqVnt30ka2Ylt3RisEPlS7DhXCv85AVTkshXZtwvwF/jIBj2HVN/6WOMPO2I04TvZRf2RNo3sTpFa4h0/FVjL91ZW3Dww8UmGvrWwC10I9M1SV9/z+fcioc7k8wtWGxVFUK+gYPSRjUJfiEovOR9w98a6BMJ0MgeorbWbIFp8Rm0xoXXuyOc9+x6l2p1FFYYZ92zi+WVvmXWpCrLH+SD7VFs7HyMlCErcMUbanHNp/iZWj4gyroYiGuiXQJxEN2mvWyQV0j9d/GluKiYzEK6Xf5ZZwdenFBkBaN2ED3iw7hXp+UOUVMgysPWp0kZd/nOpvC8V8LdkotaiivhiwUEXuz8bW6cpA==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: aug-cicd
    type: Opaque
status: {}
